export const FETCHING_COIN_DATA = "FETCHING_COIN_DATA";
export const FETCHING_COIN_DATA_SUCCESS = "FETCHING_COIN_DATA_SUCCESS";
export const FETCHING_COIN_DATA_FAIL = "FETCHING_COIN_DATA_FAIL";
export const FETCH_SINGLE_COIN_DATA = "FETCH_SINGLE_COIN_DATA";
export const FETCH_SINGLE_COIN_DATA_SUCCESS = "FETCH_SINGLE_COIN_DATA_SUCCESS";
export const FETCH_SINGLE_COIN_DATA_FAILURE = "FETCH_SINGLE_COIN_DATA_FAILURE";
